What are ufuncs?


ufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object.

Why use ufuncs?


ufuncs are` used to implement vectorization in NumPy which is way faster than iterating over elements.`

They also provide broadcasting and additional methods like reduce, accumulate etc. that are very helpful for computation.

 ### ufuncs also take additional arguments, like:

#### where  - boolean array or condition defining where the operations should take place.

### dtype -  defining the return type of elements.

### out   -  output array where the return value should be copied.

What is Vectorization?


Converting iterative statements into a vector based operation is called vectorization.



It is faster as modern CPUs are optimized for such operations.

In [1]:
#  the task is to add  two iterable into another iterable 

a=[1,2,3,4,5,6]
b=[1,2,3,4,5,6]
z=[]
for i,j in zip(a,b):
    z.append(i+j)
z

[2, 4, 6, 8, 10, 12]

### `NumPy has a ufunc for this, called add(x, y) that will produce the same result.`

In [2]:
# the above code take loop to complete the task it take to loop in one by one instance of the loop we can use the numpy function add 
import numpy as np

z = np.add(a,b)
z
# add is fun that is under the package in numpy


array([ 2,  4,  6,  8, 10, 12])

How To Create Your Own ufunc


To create your own ufunc, you have to define a function, like you do with normal functions in Python, then you add it to your NumPy ufunc library with the frompyfunc() method.



The frompyfunc() method takes the following arguments:

### `function - the name of the function.`
### `inputs - the number of input arguments (arrays).`
### `outputs - the number of output arrays.`

In [9]:
import numpy as np

def add(x,y) :
    return x * y

def sub(x,y) :
    return x - y


add = np.frompyfunc(add,2,1)
print(add([1,2,3,4],[1,2,3,4]))
print(type(add))
# it's type is numpy.unfunc 
# see the type of sub funtion it print it as a normal function
print(type(sub))

[1 4 9 16]
<class 'numpy.ufunc'>
<class 'function'>


## `Simple Arithmetic`

in this Simple Arithmetic they are some function the function are 
 ## `*Addition`
 ## `*Subtraction`
 ## `*Multiplication`
 ## `*Division`
 ## `*power`
 ## `*remainder`
 ## `*quotient`
 ## `*mod & quotient`
 ## `*absolute`

In [10]:
# additional fun using add() fun

import numpy as np


a=[1,2,3,4,5,6,7,8,9,1]
b=[5,6,7,8,9,1,1,1,3,4]
newarr=np.add(a,b)
newarr

array([ 6,  8, 10, 12, 14,  7,  8,  9, 12,  5])

In [12]:
# subtract fun using subtract() fun

import numpy as np


a=[1,2,3,4,5,6,7,8,9,1]
b=[5,6,7,8,9,1,1,1,3,4]
newarr=np.subtract(a,b)
newarr

array([-4, -4, -4, -4, -4,  5,  6,  7,  6, -3])

In [13]:
# multiplication fun using multiply() fun

import numpy as np


a=[1,2,3,4,5,6,7,8,9,1]
b=[5,6,7,8,9,1,1,1,3,4]
newarr=np.multiply(a,b)
newarr

array([ 5, 12, 21, 32, 45,  6,  7,  8, 27,  4])

In [18]:
# divide fun using divide() fun

import numpy as np


a=[1,2,3,4,5,6,7,8,9,1]
b=[5,6,7,8,9,1,1,1,3,4]
newarr=np.divide(b,a)
newarr


array([5.        , 3.        , 2.33333333, 2.        , 1.8       ,
       0.16666667, 0.14285714, 0.125     , 0.33333333, 4.        ])

In [19]:
# power fun using power() fun

import numpy as np


a=[1,2,3,4,5,6,7,8,9,1]
b=[5,6,7,8,9,1,1,1,3,4]
newarr=np.power(a,b)
newarr


array([      1,      64,    2187,   65536, 1953125,       6,       7,
             8,     729,       1])

In [21]:
# mod fun using mod() fun   remainder and mod() both shows the same result it show the remainder of the arrays 

import numpy as np


a=[2]
b=[2]
newarr=np.mod(b,a)
newarr
# it show the remainder of the following array

array([0])

In [22]:
# mod fun using mod() fun   remainder and mod() both shows the same result it show the remainder of the arrays 

import numpy as np


a=[2]
b=[2]
newarr=np.remainder(b,a)
newarr
# it show the remainder of the following array

array([0])

`Quotient and Mod`


The divmod() function return both the quotient and the the mod. The return value is two arrays, the first array contains the quotient and second array contains the mod.

In [23]:
# qutient mod fun using quotientmod divmod() fun

import numpy as np


a=[1,2,3,4,5,6,7,8,9,1]
b=[5,6,7,8,9,1,1,1,3,4]
newarr=np.divmod(a,b)
newarr


(array([0, 0, 0, 0, 0, 6, 7, 8, 3, 0]), array([1, 2, 3, 4, 5, 0, 0, 0, 0, 1]))

In [26]:
# absolute value fun using abs() fun

import numpy as np


a=[-49,-1]
newarr=np.absolute(a)
newarr


array([49,  1])

Rounding Decimals
There are primarily five ways of rounding off decimals in NumPy:

###  `truncation`
###  `fix`
###  `rounding`
###  `floor`
### ` ceil`

Truncation
Remove the decimals, and return the float number closest to zero. Use the` trunc()` and `fix() functions`.

In [41]:
import numpy as np

a=[-2.5523,-4.167]
x=np.trunc(a)
print(type(x))
x


<class 'numpy.ndarray'>


array([-2., -4.])

In [33]:
import numpy as np


x=np.fix([-2.5523,-4.167])
print(type(x))
x

array([-2., -4.])

In [37]:
# rounding it just rounding 
import numpy as np


x=np.round([-2.5523,-4.198],2)
print(type(x))
x

array([-2.55, -4.2 ])

Floor

The floor() function rounds off decimal to nearest lower integer.

E.g. floor of 3.166 is 3.

In [39]:
import numpy as np


x=np.floor([-2.5523,-4.167])
print(type(x))
x

array([-3., -5.])

Ceil


The ceil() function rounds off decimal to nearest upper integer.

E.g. ceil of 3.166 is 4.

In [42]:
import numpy as np

arr = np.ceil([-3.1666, 3.6667])
print(type(x))
print(arr)

<class 'numpy.ndarray'>
[-3.  4.]


## `Logs`
NumPy provides functions to perform log at the base 2, e and 10.

We will also explore how we can take log for any base by creating a custom ufunc.

All of the log functions will place -inf or inf in the elements if the log can not be computed.

Log at Base 2


Use the log2() function to perform log at the base 2.

In [43]:
import numpy as np

s=np.arange(1,10,2)
s
# arange it just put the number start and end and step
#  i1 is included and 10 is excluded

array([1, 3, 5, 7, 9])

In [45]:
d=np.log2(s)
d

array([0.        , 1.5849625 , 2.32192809, 2.80735492, 3.169925  ])

In [47]:
# log the base of 10
# Log at Base 10
# Use the log10() function to perform log at the base 10.


d=np.log10(s)
d

array([0.        , 0.47712125, 0.69897   , 0.84509804, 0.95424251])

In [49]:
# Natural Log, or Log at Base e
# Use the log() function to perform log at the base e.

d=np.log(s)
d

array([0.        , 1.09861229, 1.60943791, 1.94591015, 2.19722458])

In [53]:
# Log at Any Base
# NumPy does not provide any function to take log at any base, so we can use the frompyfunc() function along with inbuilt function math.log() with two input parameters and one output parameter:


import numpy as np
from math import log

d=np.frompyfunc(log,2,1)
d(100,5)

2.8613531161467867

##  Summations

In [55]:
# normal add() in numpy 

import numpy as np 

a=(1,2,3,4)  # in the input must be in tuple or typecast to list
b=(1,2,3,4)
z=np.add(a,b)
z

array([2, 4, 6, 8])

In [63]:
# summations fun in numpy

z=np.sum([a,b])
print(type(z))

<class 'numpy.int32'>


In [67]:
# we can sum in the axis also for that you need to decalre the axis, axis is nthing but it is dimension

a=([1,3,4])
b=([1,2,4])

a=np.sum([a,b],axis=1)
a

array([8, 7])

Cummulative Sum

Cummulative sum means partially adding the elements in array.

E.g. The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].

Perfom partial sum with the cumsum() function.

In [70]:
a=[(1,2,3,4,5,6,7,8,9,10,11,12)]
b=[(1,2,3,4,5,6,7,8,9,10,11,12)]
# using cummulative sum

z=np.cumsum(a)  # it store a single argument 
z

# 1,1+2,3+3,6+4,10+5  like this happings inside the cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66, 78])

## `Products`
To find the product of the elements in an array, use the prod() function.  

its similar to the `summation summation function() is done with addition and product functions() is deal with multiplication`

In [73]:
import numpy as np

a=([1,2])

b=([1,2])

z=np.prod([a,b])
z

4

In [75]:
# product through axis 


z=np.prod([a,b],axis=1)
z

array([2, 2])

`Cummulative Product`

Cummulative product means taking the product partially.

E.g. The partial product of [1, 2, 3, 4] is [1, 1*2, 1*2*3, 1*2*3*4] = [1, 2, 6, 24]

Perfom partial sum with the cumprod() function.

In [77]:
z=np.cumprod([a])
z

array([1, 2])

## `Differences`


A discrete difference means subtracting two successive elements.

E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]

To find the discrete difference, use the diff() function.

In [79]:
import numpy as np

a=[1,2,3]
z=np.diff(a)
z

array([1, 1])

## Differences

A discrete difference means subtracting two successive elements.

E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]

To find the discrete difference, use the diff() function.

In [82]:
import numpy as np

arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr, n=2)


print(newarr)

[  5 -30]
